
//G_TOKEN_OFFICE=${{secrets.G_TOKEN_OFFICE}}
console.log(`G_TOKEN_OFFICE:`, process.env.G_TOKEN_OFFICE);

//G_CREDENTIALS_GDRIVE_MOVER=${{secrets.G_CREDENTIALS_GDRIVE_MOVER}}
console.log(`G_CREDENTIALS_GDRIVE_MOVER:` , process.env.G_CREDENTIALS_GDRIVE_MOVER);

//ORIGIN_FOLDER_ID=${{secrets.ORIGIN_FOLDER_ID}}
console.log(`ORIGIN_FOLDER_ID:`, process.env.ORIGIN_FOLDER_ID);

//DESTINATION_DRIVE_ID=${{secrets.DESTINATION_DRIVE_ID}}
console.log(`DESTINATION_DRIVE_ID:`, process.env.DESTINATION_DRIVE_ID);

//DESTINATION_FOLDER_ID=${{secrets.DESTINATION_FOLDER_ID}}
console.log(`DESTINATION_FOLDER_ID:`, process.env.DESTINATION_FOLDER_ID);

//MEET_SHEET_ID=${{secrets.MEET_SHEET_ID}}
console.log(`MEET_SHEET_ID:`, process.env.MEET_SHEET_ID);

//G_SHEET_NB_CREDENTIALS=${{secrets.G_SHEET_NB_CREDENTIALS}}
console.log(`G_SHEET_NB_CREDENTIALS:`, process.env.G_SHEET_NB_CREDENTIALS);

//G_SHEET_NB_TOKEN=${{secrets.G_SHEET_NB_TOKEN}}
console.log(`G_SHEET_NB_TOKEN:`, process.env.G_SHEET_NB_TOKEN);

//YOUTUBE_DS_CREDENTIALS=${{secrets.YOUTUBE_DS_CREDENTIALS}}
console.log(`YOUTUBE_DS_CREDENTIALS:`, process.env.YOUTUBE_DS_CREDENTIALS);

//YOUTUBE_POS_BACKUP_TOKEN=${{secrets.YOUTUBE_POS_BACKUP_TOKEN}}
console.log(`YOUTUBE_POS_BACKUP_TOKEN:`, process.env.YOUTUBE_POS_BACKUP_TOKEN);

//YOUTUBE_POS_BACKUP_TOKEN_SUB=${{secrets.YOUTUBE_POS_BACKUP_TOKEN_SUB}}
console.log(`YOUTUBE_POS_BACKUP_TOKEN_SUB:`, process.env.YOUTUBE_POS_BACKUP_TOKEN_SUB);

//YOUTUBE_POS_TOKEN=${{secrets.YOUTUBE_POS_TOKEN}}
console.log(`YOUTUBE_POS_TOKEN:`, process.env.YOUTUBE_POS_TOKEN);