name: G2G SYNC 毎日17:30,21:30,24:30 (の予定)に起動
# +9時間 2021/10/3

# on:
#   schedule:
#   - cron:  '30 8,12,15 * * *'

on:
  push:
    branches: [ main ]
    # プッシュ時に動作する

jobs:
  build:

    # このジョブのために ubuntu サーバーを準備
    # まっさらなサーバーなので、以下で Node.js 自体の準備や npm install を行う
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [17.x]

    # 以下が実際のステップ
    steps:

    # この例では、v2 を使用することにより、チェックアウトアクションの安定版を確実に使用するようにしています
    - uses: actions/checkout@v2
    # Node.js 17.x のセットアップ
    - name: Use Node.js 17.x
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'
    # package.json を参考にインストールがはじまる、この場合は axios がインストール    
    - name: yarn install command
      run: yarn install

    - name: start action...
      run: > 
        G_TOKEN_OFFICE=${{secrets.G_TOKEN_OFFICE}}
        G_CREDENTIALS_GDRIVE_MOVER=${{secrets.G_CREDENTIALS_GDRIVE_MOVER}}
        YOUTUBE_DS_CREDENTIALS=${{secrets.G_CREDENTIALS_GDRIVE_MOVER}}         
        node app.js
      
      # run: export G_TOKEN_OFFICE=${{secrets.G_TOKEN_OFFICE}}
      # run: export G_CREDENTIALS_GDRIVE_MOVER=${{secrets.G_CREDENTIALS_GDRIVE_MOVER}}
      # run: export YOUTUBE_DS_CREDENTIALS=${{secrets.G_CREDENTIALS_GDRIVE_MOVER}} 
      # run: export YOUTUBE_POS_BACKUP_TOKEN=${{secrets.YOUTUBE_POS_BACKUP_TOKEN}} 
      # run: export YOUTUBE_POS_BACKUP_TOKEN_SUB=${{secrets.YOUTUBE_POS_BACKUP_TOKEN_SUB}} 
      # run: export YOUTUBE_POS_TOKEN=${{YOUTUBE_POS_TOKEN}} 
      # run: export ORIGIN_FOLDER_ID=${{secrets.ORIGIN_FOLDER_ID}} 
      # run: export DESTINATION_FOLDER_ID=${{secrets.DESTINATION_FOLDER_ID}} 
      # run: export MEET_SHEET_ID=${{secrets.MEET_SHEET_ID}} 
      # run: export G_SHEET_N0BI_CREDENTIALS=${{secrets.G_SHEET_N0BI_CREDENTIALS}} 
      # run: export G_SHEET_N0BI_TOKEN=${{G_SHEET_N0BI_TOKEN}} 
      # run: node app.js